name: tech_knowl_edge_connect
description: Education app for learning in school and university.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.6+1

environment:
  sdk: ">=3.1.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^3.15.1
  firebase_auth: ^6.0.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^5.6.11
  font_awesome_flutter: ^10.6.0
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  smooth_page_indicator: ^1.1.0
  lottie: ^3.0.0
  confetti: ^0.7.0
  collection: ^1.18.0
  dart_openai: ^5.1.0
  envied: ^0.5.3
  intl: ^0.20.2
  image_picker: ^1.0.8
  permission_handler: ^11.3.1
  firebase_storage: ^12.4.9
  uuid: ^4.4.0
  easy_image_viewer: ^1.5.1
  video_player: ^2.10.0
  video_player_web: ^2.3.5
  sign_in_with_apple: ^6.1.2
  url_launcher: ^6.3.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/icon/icon.png"
  adaptive_icon_background: "images/icon/ic_launcher_background.png"
  adaptive_icon_foreground: "images/icon/ic_launcher_foreground.png"
  web:
    generate: true
    image_path: "images/icon/icon.png"
  macos:
    generate: true
    image_path: "images/icon/icon.png"
  windows:
    generate: true
    image_path: "images/icon/icon.png"

flutter_native_splash:
  background_image: images/icon/ic_launcher_background.png
  image: images/icon/ic_launcher_foreground.png
  android_12:
    image: images/icon/ic_launcher_foreground.png
    color: "#11b1c3"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  envied_generator: ^0.5.3
  build_runner: ^2.4.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/apple.png
    - images/google.png
    - images/animations/rocket_animation.json
    - images/animations/technology_animation.json
    - images/animations/knowledge_animation.json
    # https://www.cleanpng.com/png-thinking-technologys-potential-symbolized-by-man-o-7947404/download-png.html
    - images/learning_bites/math/numbers_naming/numbers.png
    # <a href='https://pngtree.com/freepng/this-planet-fantasy-and-rocket-landmark_4123956.html'>png image from pngtree.com/</a>
    - images/rocket.png
    - images/technology.png
    - images/knowledge.png
    - images/learning_bites/education_science/motivation/motivation.png
    - images/learning_bites/biology/amphibians_cycle.png
    - images/learning_bites/biology/biver.png
    - images/learning_bites/biology/bubble.png
    - images/learning_bites/biology/carnivore_teeth.png
    - images/learning_bites/biology/carnivore_wolf.png
    - images/learning_bites/biology/carnivore.png
    - images/learning_bites/biology/crocodile_cycle.png
    - images/learning_bites/biology/early_insectivore.png
    - images/learning_bites/biology/fish_circle.png
    - images/learning_bites/biology/fish_long.png
    - images/learning_bites/biology/fish_side.png
    - images/learning_bites/biology/frugivore.png
    - images/learning_bites/biology/herbivore_biber.png
    - images/learning_bites/biology/herbivore_gras.png
    - images/learning_bites/biology/herbivore_teeth.png
    - images/learning_bites/biology/human_cycle.png
    - images/learning_bites/biology/human_heart.png
    - images/learning_bites/biology/insectivore.png
    - images/learning_bites/biology/mammals_cycle.png
    - images/learning_bites/biology/omnivore_teeth.png
    - images/learning_bites/biology/omnivore.png
    - images/learning_bites/biology/piscivore.png
    - images/learning_bites/biology/rabbit.png
    - images/learning_bites/biology/reptiles_cycle.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
