// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnka7UErIVm7Sj7N4aP8QHwZlwRiduWh4',
    appId: '1:31090418784:web:63de8b9acf9d68f977cf05',
    messagingSenderId: '31090418784',
    projectId: 'tech-knowl-edge-connect',
    authDomain: 'tech-knowl-edge-connect.firebaseapp.com',
    storageBucket: 'tech-knowl-edge-connect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4po_-2wO2OqwZOnW22zGEwvde6QMfF0s',
    appId: '1:31090418784:android:21094b8ea780f3d977cf05',
    messagingSenderId: '31090418784',
    projectId: 'tech-knowl-edge-connect',
    storageBucket: 'tech-knowl-edge-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY-GrbGHrII6HESm3wRZfcBk_HoVOh-zg',
    appId: '1:31090418784:ios:5c461798510f84a277cf05',
    messagingSenderId: '31090418784',
    projectId: 'tech-knowl-edge-connect',
    storageBucket: 'tech-knowl-edge-connect.appspot.com',
    iosBundleId: 'com.example.techKnowlEdgeConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY-GrbGHrII6HESm3wRZfcBk_HoVOh-zg',
    appId: '1:31090418784:ios:26ad4a5bf0fabbf877cf05',
    messagingSenderId: '31090418784',
    projectId: 'tech-knowl-edge-connect',
    storageBucket: 'tech-knowl-edge-connect.appspot.com',
    iosBundleId: 'com.example.techKnowlEdgeConnect.RunnerTests',
  );
}
