// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn6UyrW36DXoY9lrUBRjIqn-Xhabt_sbs',
    appId: '1:31090418784:web:63de8b9acf9d68f977cf05',
    messagingSenderId: '31090418784',
    projectId: 'tech-knowl-edge-connect',
    authDomain: 'tech-knowl-edge-connect.firebaseapp.com',
    storageBucket: 'tech-knowl-edge-connect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr3c4veWbLDjqVUnKJRcJ6QpFyr8uRBKY',
    appId: '1:31090418784:android:c6e2431b3b9cc4d277cf05',
    messagingSenderId: '31090418784',
    projectId: 'tech-knowl-edge-connect',
    storageBucket: 'tech-knowl-edge-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjmobNIjYeak7YS5Hww98tnc7AMeb1XHs',
    appId: '1:31090418784:ios:c565ee0244fea1cc77cf05',
    messagingSenderId: '31090418784',
    projectId: 'tech-knowl-edge-connect',
    storageBucket: 'tech-knowl-edge-connect.appspot.com',
    androidClientId:
        '31090418784-mlpa9in81cp77nv56k0uvss3dpklrc5n.apps.googleusercontent.com',
    iosClientId:
        '31090418784-3gcsv6ltf60llhe861j7um1m7kntmet9.apps.googleusercontent.com',
    iosBundleId: 'com.jenslemke.techKnowlEdgeConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjmobNIjYeak7YS5Hww98tnc7AMeb1XHs',
    appId: '1:31090418784:ios:c565ee0244fea1cc77cf05',
    messagingSenderId: '31090418784',
    projectId: 'tech-knowl-edge-connect',
    storageBucket: 'tech-knowl-edge-connect.appspot.com',
    androidClientId:
        '31090418784-mlpa9in81cp77nv56k0uvss3dpklrc5n.apps.googleusercontent.com',
    iosClientId:
        '31090418784-3gcsv6ltf60llhe861j7um1m7kntmet9.apps.googleusercontent.com',
    iosBundleId: 'com.jenslemke.techKnowlEdgeConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn6UyrW36DXoY9lrUBRjIqn-Xhabt_sbs',
    appId: '1:31090418784:web:57fc5d5ac06ccb4977cf05',
    messagingSenderId: '31090418784',
    projectId: 'tech-knowl-edge-connect',
    authDomain: 'tech-knowl-edge-connect.firebaseapp.com',
    storageBucket: 'tech-knowl-edge-connect.appspot.com',
  );
}
