import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:tech_knowl_edge_connect/components/user/user_constants.dart';
import 'package:tech_knowl_edge_connect/models/learning_bite.dart';
import 'package:tech_knowl_edge_connect/services/content_service.dart';

class LearningBiteDialog extends StatefulWidget {
  final String subjectId;
  final String categoryId;
  final String topicId;
  final String unitId;
  final String conceptId;
  final LearningBite? learningBite;

  const LearningBiteDialog({
    super.key,
    required this.subjectId,
    required this.categoryId,
    required this.topicId,
    required this.unitId,
    required this.conceptId,
    this.learningBite,
  });

  @override
  State<LearningBiteDialog> createState() => _LearningBiteDialogState();
}

class _LearningBiteDialogState extends State<LearningBiteDialog> {
  final ContentService _contentService = ContentService();
  final nameController = TextEditingController();
  IconData selectedIcon = UserConstants.availableIcons.values.first;
  late String _currentStatus;
  bool _isDirty = false;
  String? _errorText;

  @override
  void initState() {
    super.initState();
    if (widget.learningBite != null) {
      nameController.text = widget.learningBite!.name;
      selectedIcon = widget.learningBite!.iconData;
      _currentStatus = widget.learningBite!.status;
    } else {
      _currentStatus = UserConstants.statusPrivate;
    }
    nameController.addListener(_markAsDirty);
  }

  void _markAsDirty() {
    if (!mounted) return;
    setState(() {
      if (nameController.text.isNotEmpty) {
        _errorText = null;
      }
      _isDirty = true;
    });
  }

  @override
  void dispose() {
    nameController.removeListener(_markAsDirty);
    nameController.dispose();
    super.dispose();
  }

  Future<void> _save(String status) async {
    if (nameController.text.trim().isEmpty) {
      if (mounted) {
        setState(() {
          _errorText = 'Name darf nicht leer sein';
        });
      }
      return;
    }
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return;

    if (widget.learningBite == null) {
      // Create
      final newItem = LearningBite(
        id: '', // Generated by Firestore
        name: nameController.text,
        type: 'lesson',
        content: [],
        iconData: selectedIcon,
        authorId: user.uid,
        status: status,
      );
      await _contentService.addLearningBite(
        widget.subjectId,
        widget.categoryId,
        widget.topicId,
        widget.unitId,
        widget.conceptId,
        newItem,
      );
    } else {
      // Update
      await _contentService.updateLearningBite(
        widget.subjectId,
        widget.categoryId,
        widget.topicId,
        widget.unitId,
        widget.conceptId,
        widget.learningBite!.id,
        {
          'title': nameController.text, // Mapped to 'title' in Firestore
          'iconData': {
            'codePoint': selectedIcon.codePoint,
            'fontFamily': selectedIcon.fontFamily,
            'fontPackage': selectedIcon.fontPackage,
          },
          'status': status,
        },
      );
    }
    if (mounted) Navigator.pop(context);
  }

  @override
  Widget build(BuildContext context) {
    final isEditing = widget.learningBite != null;

    return AlertDialog(
      title: Text(isEditing
          ? "Learning Bite bearbeiten"
          : "Neues Learning Bite erstellen"),
      content: SizedBox(
        width: double.maxFinite,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(height: 8),
              TextField(
                controller: nameController,
                decoration: InputDecoration(
                  labelText: "Name des Learning Bites",
                  helperText: ' ',
                  errorText: _errorText,
                ),
              ),
              const SizedBox(height: 16),
              const Text("Icon wählen:",
                  style: TextStyle(fontWeight: FontWeight.bold)),
              const SizedBox(height: 8),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: UserConstants.availableIcons.values.map((icon) {
                  return GestureDetector(
                    onTap: () {
                      if (mounted) {
                        setState(() {
                          selectedIcon = icon;
                          _isDirty = true;
                        });
                      }
                    },
                    child: Container(
                      width: 40,
                      height: 40,
                      decoration: BoxDecoration(
                        color: selectedIcon == icon
                            ? Theme.of(context).colorScheme.primaryContainer
                            : null,
                        borderRadius: BorderRadius.circular(8),
                        border: selectedIcon == icon
                            ? Border.all(
                                color: Theme.of(context).colorScheme.primary,
                                width: 2)
                            : Border.all(color: Colors.grey.shade300),
                      ),
                      child: Icon(
                        icon,
                        color: selectedIcon == icon
                            ? Theme.of(context).colorScheme.primary
                            : Colors.grey,
                      ),
                    ),
                  );
                }).toList(),
              ),
              const SizedBox(height: 16),
              if (isEditing) ...[
                const Divider(),
                Row(
                  children: [
                    const Text("Status: "),
                    Chip(
                      label: Text(
                        UserConstants.statusLabels[_currentStatus] ??
                            _currentStatus,
                      ),
                      backgroundColor:
                          UserConstants.getStatusColor(_currentStatus),
                      labelStyle: const TextStyle(color: Colors.white),
                    ),
                  ],
                ),
                const SizedBox(height: 8),
                if (_currentStatus == UserConstants.statusPrivate)
                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton.icon(
                      icon: const Icon(Icons.publish),
                      label: const Text("Veröffentlichen"),
                      onPressed: () => _save(UserConstants.statusPending),
                    ),
                  ),
                if ((_currentStatus == UserConstants.statusPending ||
                    _currentStatus == UserConstants.statusApproved))
                  SizedBox(
                    width: double.infinity,
                    child: OutlinedButton.icon(
                      icon: const Icon(Icons.visibility_off),
                      label: const Text("Auf privat setzen"),
                      onPressed: () => _save(UserConstants.statusPrivate),
                    ),
                  ),
              ] else ...[
                const Text(
                    "Hinweis: Nach dem Erstellen ist der Bite noch leer.",
                    style: TextStyle(fontSize: 12, color: Colors.grey)),
                const SizedBox(height: 8),
              ],
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text("Abbrechen"),
        ),
        ElevatedButton(
          onPressed: () {
            String statusToSave = _currentStatus;
            if (widget.learningBite == null) {
              statusToSave = UserConstants.statusPrivate;
            } else {
              if (_isDirty) {
                statusToSave = UserConstants.statusPrivate;
              }
            }
            _save(statusToSave);
          },
          child: Text(isEditing ? "Speichern" : "Erstellen"),
        ),
      ],
    );
  }
}
