import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:tech_knowl_edge_connect/components/user/user_constants.dart';
import 'package:tech_knowl_edge_connect/models/subject.dart';
import 'package:tech_knowl_edge_connect/services/content_service.dart';

class SubjectDialog extends StatefulWidget {
  final Subject? subject;

  const SubjectDialog({
    super.key,
    this.subject,
  });

  @override
  State<SubjectDialog> createState() => _SubjectDialogState();
}

class _SubjectDialogState extends State<SubjectDialog> {
  final ContentService _contentService = ContentService();
  final nameController = TextEditingController();
  Color selectedColor = Colors.blueGrey;
  IconData selectedIcon = Icons.folder;
  late String _currentStatus;
  bool _isDirty = false;
  String? _errorText;

  @override
  void initState() {
    super.initState();
    if (widget.subject != null) {
      nameController.text = widget.subject!.name;
      selectedColor = widget.subject!.color;
      selectedIcon = widget.subject!.iconData;
      _currentStatus = widget.subject!.status;
    } else {
      _currentStatus = UserConstants.statusPrivate;
    }

    nameController.addListener(_markAsDirty);
  }

  void _markAsDirty() {
    if (!mounted) return;
    setState(() {
      if (nameController.text.isNotEmpty) {
        _errorText = null;
      }
      _isDirty = true;
    });
  }

  @override
  void dispose() {
    nameController.dispose();
    super.dispose();
  }

  Future<void> _save(String status) async {
    if (nameController.text.trim().isEmpty) {
      if (mounted) {
        setState(() {
          _errorText = 'Name darf nicht leer sein';
        });
      }
      return;
    }
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return;

    if (widget.subject == null) {
      // Create
      final newSubject = Subject(
        id: '', // Generated by Firestore
        name: nameController.text,
        color: selectedColor,
        iconData: selectedIcon,
        authorId: user.uid,
        status: status,
      );
      await _contentService.addSubject(newSubject);
    } else {
      // Update
      // If dirty and we are just saving, we must revert to private (unless status is explicitly forced by buttons)
      // But here we pass the desired status.
      // logic: if user clicked "Publish", status is Pending.
      // If user clicked "Save" (and is dirty), status is Private.
      // If user clicked "Save" (and not dirty), status is kept (handled by caller).

      await _contentService.updateSubject(widget.subject!.id, {
        'name': nameController.text,
        'color': selectedColor.toARGB32(),
        'iconData': {
          'codePoint': selectedIcon.codePoint,
          'fontFamily': selectedIcon.fontFamily,
          'fontPackage': selectedIcon.fontPackage,
        },
        'status': status,
      });
    }
    if (mounted) Navigator.pop(context);
  }

  @override
  Widget build(BuildContext context) {
    final isEditing = widget.subject != null;

    return AlertDialog(
      title: Text(isEditing ? "Fach bearbeiten" : "Neues Fach erstellen"),
      content: SizedBox(
        width: double.maxFinite,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              TextField(
                controller: nameController,
                decoration: InputDecoration(
                  labelText: "Name des Fachs",
                  hintText: "z.B. Mathematik",
                  helperText: ' ',
                  errorText: _errorText,
                ),
              ),
              const SizedBox(height: 16),
              const Text("Farbe wählen:",
                  style: TextStyle(fontWeight: FontWeight.bold)),
              const SizedBox(height: 8),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: UserConstants.availableColors.values.map((color) {
                  return GestureDetector(
                    onTap: () {
                      if (mounted) {
                        setState(() {
                          selectedColor = color;
                          _isDirty = true;
                        });
                      }
                    },
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        color: color,
                        shape: BoxShape.circle,
                        border: selectedColor.toARGB32() == color.toARGB32()
                            ? Border.all(
                                color: Theme.of(context).colorScheme.onSurface,
                                width: 2)
                            : null,
                      ),
                      child: selectedColor.toARGB32() == color.toARGB32()
                          ? Icon(Icons.check,
                              size: 20,
                              color: Theme.of(context).colorScheme.onPrimary)
                          : null,
                    ),
                  );
                }).toList(),
              ),
              const SizedBox(height: 16),
              const Text("Icon wählen:",
                  style: TextStyle(fontWeight: FontWeight.bold)),
              const SizedBox(height: 8),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: UserConstants.availableIcons.values.map((icon) {
                  return GestureDetector(
                    onTap: () {
                      if (mounted) {
                        setState(() {
                          selectedIcon = icon;
                          _isDirty = true;
                        });
                      }
                    },
                    child: Container(
                      width: 40,
                      height: 40,
                      decoration: BoxDecoration(
                        color: selectedIcon == icon
                            ? Theme.of(context).colorScheme.primaryContainer
                            : null,
                        borderRadius: BorderRadius.circular(8),
                        border: selectedIcon == icon
                            ? Border.all(
                                color: Theme.of(context).colorScheme.primary,
                                width: 2)
                            : Border.all(color: Colors.grey.shade300),
                      ),
                      child: Icon(
                        icon,
                        color: selectedIcon == icon
                            ? Theme.of(context).colorScheme.primary
                            : Colors.grey,
                      ),
                    ),
                  );
                }).toList(),
              ),
              const SizedBox(height: 16),
              if (isEditing) ...[
                const Divider(),
                Row(
                  children: [
                    const Text("Status: "),
                    Chip(
                      label: Text(
                        UserConstants.statusLabels[_currentStatus] ??
                            _currentStatus,
                      ),
                      backgroundColor:
                          UserConstants.getStatusColor(_currentStatus),
                      labelStyle: const TextStyle(color: Colors.white),
                    ),
                  ],
                ),
                const SizedBox(height: 8),
                if (_currentStatus == UserConstants.statusPrivate)
                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton.icon(
                      icon: const Icon(Icons.publish),
                      label: const Text("Veröffentlichen"),
                      onPressed: () => _save(UserConstants.statusPending),
                    ),
                  ),
                if ((_currentStatus == UserConstants.statusPending ||
                    _currentStatus == UserConstants.statusApproved))
                  SizedBox(
                    width: double.infinity,
                    child: OutlinedButton.icon(
                      icon: const Icon(Icons.visibility_off),
                      label: const Text("Auf privat setzen"),
                      onPressed: () => _save(UserConstants.statusPrivate),
                    ),
                  ),
              ],
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text("Abbrechen"),
        ),
        ElevatedButton(
          onPressed: () {
            // Standard save action
            // If creating, defaulting to private.
            // If editing, if dirty -> Status Private. If not dirty -> Keep status.
            String statusToSave = _currentStatus;
            if (widget.subject == null) {
              // Creating a new one
              statusToSave = UserConstants.statusPrivate;
            } else {
              // Editing
              if (_isDirty) {
                statusToSave = UserConstants.statusPrivate;
              }
            }
            _save(statusToSave);
          },
          child: Text(isEditing ? "Speichern" : "Erstellen"),
        ),
      ],
    );
  }
}
